[Task] Add Js for webpage
cmvn-thaile/FE-Internship-2023_Thai-Le-Q_FE-Exercise pull request #10
Opened 2023-08-15 10:09 UTC by cmvn-thaile

### References
- [UI Design](https://www.figma.com/file/U9a6Mp63xTJOZXV2adIZDV/Lotus?type=design&node-id=1012-250&mode=design&t=MfTxq4MLdsm1sAWj-0)

### Description
- Add JS for webpage

### Screenshot
![image](https://github.com/cmvn-thaile/FE-Internship-2023_Thai-Le-Q_FE-Exercise/assets/141292462/3acc97e2-bde6-4a89-95ea-6e50e71fc0c3)
### Checklist

- [x] Code standard convention, beautiful, easy to see
- [x] PR in the right format, branch name, clear commit
- [x] Analyze and divide reasonable layout.
- [x] Using HTML5 semantic tags
- [x] Divide modules based on each component's style
- [x] Build Grid System
- [x] Some basic <meta> tags for HTML Document.

2023-08-15 17:11 UTC, st-ngabui requested changes
Check cmts e

2023-08-15 17:11 UTC, st-ngabui commented on js/index.js
> +    btnAddToCart.addEventListener("click", function (e) {
Viết function ra riêng rồi truyền vào thôi em nghe

2023-08-15 17:11 UTC, st-ngabui commented on js/index.js
> +          localStorage.setItem("cartItems", JSON.stringify(cartItems));
Dòng code này dùng chung cho 2 case productExists or not => Tách nó ra dùng chung, ko để vào trong if, else e nha

2023-08-15 17:11 UTC, st-ngabui commented on js/index.js
> +    }, 0);
Đoạn này chị thấy đang giống func getQuantity, em có thể dùng luôn func đó thay vì viết lặp code

2023-08-15 17:11 UTC, st-ngabui commented on js/index.js
> +function getQuantity(){
Bởi vì func này có update textContent nên mình có thể đătj tên func là `updateQuantityCart` sẽ hợp lý hơn

2023-08-16 07:41 UTC, st-duynguyen approved these changes
@cmvn-thaile Tạm thời merge bài này để tụi e checkout ra làm bài tập sau. Tuị e sẽ check kĩ fix comment ở bài sau

2023-08-16 07:41 UTC, merged