[Task] Add HTML Structure To Webpage
cmvn-thaile/FE-Internship-2023_Thai-Le-Q_FE-Exercise pull request #4
Opened 2023-08-04 08:37 UTC by cmvn-thaile

### Description
- Add HTML structure based on the design 

### Checklist
- [x] App run correctly
- [x] No convention errors

2023-08-04 14:41 UTC, st-ngabui requested changes

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +    <header class="header">
Sử dụng thẻ div.container trong thẻ header để bọc các element của header lại

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <img src="#" alt="E-Shop" />
Để tối ưu cho SEO => đặt thẻ h1 cho logo
Vì logo thường là link tới trang home => sử dụng thêm thẻ a.

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <ul>
Nên đặt tên class cho thẻ `ul`, gợi ý là `nav-list`

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +          <li class="nav-items"><a href="#">Men</a></li>
Chị nghĩ nó là item thì nên bỏ kí tự "s" e nha, `nav-items => nav-item`

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +          <i class="bx bx-search-alt-2"></i>
Các icon này thường link tới 1 trang nào đó, nên e bỏ thêm thẻ a vào

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +    <section class="billboard">
section này gọi là banner, nên e đổi tên lại sẽ dễ hiểu và phù hợp hơn. (đổi cho những class bên trong section này nữa)
Ngoài ra với section mình nên đặt tên class như sau:
- class đầu là section
- class thứ 2 là section-{name_section}
=> class="section section-banner"

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +      <h1 class="billboard-title">Sale of the summer collection</h1>
Vì h1 mình để cho logo nên sẽ đổi lại thành h2 nha

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +      <button class="billboard-button">
chỗ này sẽ link tới 1 trang nào đó => dùng thẻ a

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +      <div class="billboard-features">
dùng ul, li cho những feature này e nha. Và mình sẽ đổi tên class lại cho phù hợp luôn.
Ví dụ: feature-list > feature-item

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +          <p class="features-desc">On purchases over $199</p>
Vì icon nằm bên trái, 2 dòng text kia nằm bên phải => dùng thẻ div để bọc 2 dòng text lại để sau này còn css nữa
Text bên trên nó là title của item này => nên dùng thẻ heading (h4)

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +    <article class="features-products">
Chỗ này nên dùng section nha, vì article là để chỉ bài viết. Tuy nhiên theo chị thấy thì đây không phải là bài viết.
Mình có thể đặt tên class là `section section-categories`.
Một lưu ý lặp lại là để thẻ `div.container` để bọc section này lại

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <p class="features-product-desc">New arrivalsare now in!</p>
Nội dung này như title của item => đặt thẻ heading (h4)

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +      <div class="features-product">
Lưu ý sử dụng ul, li cho section này

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <button class="features-product-btn upper-case">SHOW COLLECTION</button>
Text này sẽ move tới page nào đó => sử dụng thẻ a

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +    <section>
Đặt tên class cho section này và sử dụng div.container bên trong

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +          <p class="product-name">T-Shirt Summer Vibes</p>
Sử dụng h4 cho tên sản phẩm

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <li class="product">
Vì 1 product thường sẽ được link tới trang detail khi click vào => dùng thêm thẻ a

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +    <section>
đặt tên cho section này

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <h3 class="txt-title">Selected just for you</h3>
thẻ h3 này nếu để ý nó là title của section và được sử dụng lại ở những phần sau nữa => có thể đặt tên section-title để apply chung cho những title section khác

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <li class="service">
Vì item thứ 2 trong section có title và icon màu khác => khả năng cao click đươcj qua trang khác => dùng thẻ a

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +          <p class="service-title txt-bold">Free shipping</p>
Sử dụng h4 cho title cuả item này

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <li class="service">
Item thứ 2 có css hơi khác  những cái kia => add thêm class "service-active" để sau này css cho nó

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +      <ul class="products">
sửa giống cmt của mục Selected just for you

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +      <article class="subscribe">
mục subscribe này là 1 section e nha, footer dành cho mục màu cam phía dưới

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <input placeholder="Enter your email" class="subscribe-input" />
Lưu ý dùng thêm thẻ form

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +      <div class="shop-details">
Tách mục này là footer. Trong đó có thẻ div cho footer-top và thẻ p cho text phía dưới.
Với mục div.footer-top:
- Sử dụng thêm div.container để bọc nội dung bên trong
- Thêm 1 thẻ div cho việc css layout bên trong(theo hàng)

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +        <img src="" alt="Shop Logo" />
Vì mục hình ảnh và nội dung dưới nó là 1 cột, dùng thẻ div để nhóm lại

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +          <h3 class="info-title">Information</h3>
title dưới footer chị nghĩ ko cần phải dùng thẻ heading

2023-08-04 14:41 UTC, st-ngabui commented on index.html
> +            <li class="contact-item">Hotline: +1 131 138 138</li>
những title và item mục policy, info, contact css giống nhau => đặt chung tên class là `infor-shop-title, infor-shop-item`

2023-08-04 14:46 UTC, st-ngabui commented
Chị tóm lại những nội dung chính e cần sửa:
- Đặt tên class hợp lý hơn
- Sử dụng h1 cho banner
- Lưu ý về việc sử dụng div.container
- Sử dụng ul, li cho các danh sách
- Xem xét xem item đó có move tới page khác được không để sử dụng thẻ a
- Sử dụng thẻ form cho những form-controls
- Cách nhóm những nội dung lại cho phù hợp
- Những mục có CSS giống nhau thì mình nên đặt tên class chung

2023-08-04 14:47 UTC, st-ngabui reviewed
Chị tóm lại những nội dung chính e cần sửa:
- Đặt tên class hợp lý hơn
- Sử dụng h1 cho banner
- Lưu ý về việc sử dụng div.container
- Sử dụng ul, li cho các danh sách
- Xem xét xem item đó có move tới page khác được không để sử dụng thẻ a
- Sử dụng thẻ form cho những form-controls
- Cách nhóm những nội dung lại cho phù hợp
- Những mục có CSS giống nhau thì mình nên đặt tên class chung

2023-08-04 14:55 UTC, st-ngabui requested changes

2023-08-04 14:55 UTC, st-ngabui commented on index.html
> +
Sử dụng thẻ main để bọc nội dung chính của trang web lại, thẻ main thường là nội dung nằm giữa header và footer

2023-08-04 16:07 UTC, st-ngabui requested changes

2023-08-04 16:07 UTC, st-ngabui commented on index.html
> +        <ul class="shop-details-iconsGroup">
ul > li nên đặt tên class là social-list > social-item

2023-08-04 16:07 UTC, st-ngabui commented on index.html
> +        <div class="shop-details-policy">
Sử dụng ul>li cho 1 list các cột này nha

2023-08-05 14:41 UTC, st-ngabui requested changes
Check comment e nha, nhớ để ý thêm về cách dùng thẻ a nha

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +        <h1 class="logo"><a>E-Shop</a></h1>
Chỗ này logo là image nên e vẫn bỏ thẻ img trong thẻ a nha

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +          </h2>
Đoạn này là h2 thôi e nhé, ko phải link đâu nên ko thêm thẻ a vào nè

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +          </button>
Cái này là e dùng thẻ a thay vì button nha

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +          </button>
Cái này là e dùng thẻ a thay vì button nha

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +            </ul>
ul sẽ chứa 3 item. Trong đó 1 item li bao gồm icon và text e nha. E phân tích ul, li đoạn này sai rồi.
`Free shipping` là name => đặt thẻ h4 thay vì thẻ p

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +              </h4>
Chỗ này chỉ là text thôi ko phải link => ko dùng thẻ a e nha

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +              </button>
Dùng thẻ a thay vì button nha, vì thẻ a sẽ link tới 1 trang nào đó

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +                <h4p class="product-name">T-Shirt Summer Vibes</h4p>
Tên thẻ đang sai nè e

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +                <p class="product-price">$99,99</p>
Mặc dù ở đây có 1 price thôi nhưng e vẫn nên dùng thẻ div bọc nó lại giống như khi có discount nha

2023-08-05 14:41 UTC, st-ngabui commented on index.html
> +            <li class="shop-details-infor">
ul là `shop-details-list` thì li nên là `shop-details-item` nè e

2023-08-05 14:50 UTC, cmvn-thaile commented on index.html
> +        <h1 class="logo"><a>E-Shop</a></h1>
tức là em để thẻ <h1 class="logo"><a><img src="" alt="logo" /></a></h1> vậy hả chị :v tại em thấy hơi lạ

2023-08-06 02:20 UTC, st-ngabui requested changes

2023-08-06 02:20 UTC, st-ngabui commented on index.html
> +            <button class="upper-case">SHOW MORE</button>
Chỗ này dùng thẻ a em nha

2023-08-06 08:54 UTC, st-ngabui requested changes
check cmt e nha

2023-08-06 08:54 UTC, st-ngabui commented on index.html
> +        <h1 class="logo"><a><img src="assets/img/logo.png" alt="E-Shop"></a></h1>
Đoạn này e xuống hàng sau thẻ mở cho dễ nhìn
Thêm thuộc tính href cho thẻ a, check lại những chỗ khác nữa nha

2023-08-06 08:54 UTC, st-ngabui commented on index.html
> +              <span class="feature-item"><i class="bx bxs-truck"></i></span>
Sau khi xác định được thẻ ul, li thì e nên đặt tên class cho nó hợp lý, list thì cho ul, item cho li.
Vì dụ:
```
<ul class="banner-features feature-list>
   <li class="feature-item>
      <div class="feature-img">
         <i class="bx bxs-truck"></i>
      </div>
      <div class="feature-detail">
         <h4 class="feature-name">Free shipping</h4>
         <p class="feature-desc">On purchases over $199</p>
      </div>
   </li>
</ul>

```

2023-08-06 08:54 UTC, st-ngabui commented on index.html
>              <li class="features-product-item">
section ở đây đang là category => e sửa lại tên những class của những element trong đó từ `features-product-{} => category-{}` để cho nó đồng nhất

2023-08-07 02:00 UTC, st-ngabui requested changes

2023-08-07 02:00 UTC, st-ngabui commented on index.html
> +                <a href=""><i class="bx bxl-facebook"></i></a>
E add thêm class cho thẻ a nha, check lại những chỗ khác nữa nè

2023-08-07 12:39 UTC, st-ngabui requested changes

2023-08-07 12:39 UTC, st-ngabui commented on index.html
> +              <span class="feature-img"
Chỗ ni nên dùng thẻ div e nha

2023-08-07 12:39 UTC, st-ngabui commented on index.html
> +            <a class="category-btn" href="">SHOW MORE</a>
Class chỗ ni sao lại có category đây e nhở

2023-08-07 12:39 UTC, st-ngabui commented on index.html
> +            <li class="service">
Chỗ ni e dùng class dạng service-list > service-item nha

2023-08-07 12:39 UTC, st-ngabui commented on index.html
> +        <hr />
Bỏ hr đi vì không cần thiết e nghe

2023-08-07 12:50 UTC, st-ngabui approved these changes
Thank you! LGTM

2023-08-07 23:28 UTC, merged