[Task] Add css to html
cmvn-thaile/FE-Internship-2023_Thai-Le-Q_FE-Exercise pull request #6
Opened 2023-08-08 10:44 UTC by cmvn-thaile

### Description
- [E-shop web design](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?type=design&node-id=8-194&mode=design&t=7JWk5FpX4LDVVyOw-0)
- Add CSS for E-Shop web
###Screenshot
![screencapture-file-E-project-cmvn-FE-Internship-2023-Thai-Le-Q-FE-Exercise-index-html-2023-08-08-17_43_29](https://github.com/cmvn-thaile/FE-Internship-2023_Thai-Le-Q_FE-Exercise/assets/141292462/744f02c4-1769-4bb2-a625-08e597cebb89)
### Checklist
- [x] App run correctly
- [x] The code has been tested in the local environment.
- [x] No convention errors

2023-08-08 15:12 UTC, st-trangnguyen requested changes
- Tổng thể cách làm css của em chưa có các cách làm tối ưu dẫn đến code khá rườm rà và nhiều cái không cần thiết
- Cách viết code có biết gom nhóm các thuộc tính dễ đọc hiểu

Cần improve:
- chưa tạo được variable cho color
- chưa tạo được các module cho button, badge, text... ví dụ `btn btn-primary` `btn btn-secondary` `badge badge-danger`.... em tham khảo thêm bootstrap
- Về cái line-height em để ý sẽ có từng cặp như sau

```
font-size: 16px;
line-height: 24px;
```
```
font-size: 14px;
line-height: 21px;
```
suy ra line-height sẽ = font-size * 1.5. Vậy nên em chỉ cần set line-height: 1.5 ở body ko cần set cho từng element.

2023-08-08 15:12 UTC, st-trangnguyen commented on index.html
> +    <link rel="stylesheet" href="./style/main.css" />
Rank B: Em import file chứa những common style trước, rồi mới đến file của các page chính

2023-08-08 15:12 UTC, st-trangnguyen commented on index.html
> +      <div
Rank B: ko add helper class, các class khác vào container

2023-08-08 15:12 UTC, st-trangnguyen commented on index.html
> +          <ul class="nav-list flex justify-space-between">
Rank C: d-flex instead of flex rõ nghĩa hơn

2023-08-08 15:12 UTC, st-trangnguyen commented on style/sub.css
> +.section {
Rank C: cái này ko cần thiết

2023-08-08 15:12 UTC, st-trangnguyen commented on style/sub.css
> +.col-1 {
Rank C: đóng col này e dùng 1 kiểu xác định width hoy

2023-08-08 15:12 UTC, st-trangnguyen commented on style/main.css
> +  padding: 20px 20px;
Rank B: e check lại chỗ này nha

2023-08-08 15:12 UTC, st-trangnguyen commented on style/main.css
> +.search-icon {
Rank A: chỗ đống icon này bị lặp code

2023-08-08 15:12 UTC, st-trangnguyen commented on style/main.css
> +.banner-highlight {
Rank B: em tạo common class `text-primary` sau này cứ text nào có màu vàng primary của app là dùng chung đc

2023-08-08 15:12 UTC, st-trangnguyen commented on style/main.css
> +.banner-features {
Rank C: Chỗ này e làm chưa được đúng lắm dẫn đến việc phải hack padding margin, tạm thời ignore có thời gian nghiền ngẫm cách làm chỗ banner ok hơn

2023-08-08 15:12 UTC, st-trangnguyen commented on style/main.css
> +.feature-list {
Rank B: em check lại đoạn style flex chỗ này nhé, vừa dùng class vừa dùng css

2023-08-08 15:12 UTC, st-trangnguyen commented on style/main.css
> +.category-1 {
Rank B: List category này cách e style không đúng, dẫn đến code rất nhiều mà lại không giống design

2023-08-09 08:07 UTC, cmvn-thaile commented on style/main.css
> +.category-1 {
Em có sửa lại rồi ạ, chị có thời gian thì review lại cho em với. Em cảm ơn

2023-08-10 05:43 UTC, merged